updated to just be KBI addition
kaleido-io/terraform-provider-kaleido pull request #60
Opened 2024-04-15 16:13 UTC by trevorsc19

removed signer vs non-signer node types for now until EVM gateway updates. This change just simply adds KBI to both the platform_stack and multiparty_platform_stack examples

2024-04-17 14:25 UTC, peterbroadhurst requested changes
We've got some changes upstream in `v1.1` that are ahead of `rc2` that mean this won't work with the latest provider.

Could you do a test with a local build of the provider, configured via a `.terraformrc` please @trevorsc19 ?

2024-04-17 14:25 UTC, peterbroadhurst commented on examples/platform_stack/main.tf
> +    name: erc20_indexer
Think this reverts a change in https://github.com/kaleido-io/terraform-provider-kaleido/pull/58

2024-04-18 20:41 UTC, trevorsc19 commented
Took me a minute to troubleshoot some local build issues, but I believe this is good now. It does not overwrite the more recent changes to v1.1 and also adds in block indexer to the basic builds.
@peterbroadhurst Please review when you get a chance

2024-04-18 20:52 UTC, peterbroadhurst approved these changes
Thanks @trevorsc19 👍

2024-04-18 20:52 UTC, merged